// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/0032c9b7e50f6105a33e645168091dd2f8126a5f/latinize/latinize.d.ts
declare namespace LatinizeModule {
    export interface Latinize {
        (str: string): string;
        characters: { [char: string]: string };
    }
}


declare module "latinize" {
    let latinize: LatinizeModule.Latinize;
    export = latinize;
}
