version: "3.0"
services:
   mongodb:
     image: mongo
     expose:
       - "27017"
     environment:
       - MONGO_INITDB_DATABASE=modestidb
#       - MONGO_INITDB_ROOT_USERNAME=root
#       - MONGO_INITDB_ROOT_PASSWORD=SuchAVeryLongMongoPasswd!
     volumes:
       - ../docker/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     networks:
       - backend
   timrefdb:
     build: ../docker/plugin-timrefdb/
     image: gitlab-registry.cern.ch/modesti/modesti-server-timrefdb
     volumes:
       - ./modesti/modesti.properties:/opt/modesti/modesti.properties
     depends_on: 
       - mongodb
     ports:
       - "8080:8080"
     networks:
       - backend
       - frontend
  #mongo-express:
  #  image: mongo-express
  #  restart: always
  #  ports:
  #    - "8081"
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: SuchAVeryLongMongoPasswd!
  #  networks:
  #     - backend
  #     - frontend
networks:
  backend:
    driver: "bridge"
  frontend:
