stages:
- build
- sonar_preview
- deploy
- sonar

# Fully build and publish master branch
build_and_publish:
  stage: build
  script:
    - ./gradlew clean --refresh-dependencies -PartifactoryUser=${ARTIFACTORY_USERNAME} -PartifactoryPassword=${ARTIFACTORY_PASSWORD}
  only:
    - master

# Just run tests on feature branches
build:
  stage: build
  script:
    - ./gradlew clean test --refresh-dependencies -PartifactoryUser=${ARTIFACTORY_USERNAME} -PartifactoryPassword=${ARTIFACTORY_PASSWORD}
  except:
    - master

deploy_test:
  stage: deploy
  script:
    - source ./gradle.properties; ssh timtest@modesti-test.cern.ch "~/scripts/deploy-modesti-server-test.sh $version"
    - ssh timtest@modesti-test.cern.ch '/usr/opt/bin/wreboot -N MODESTI-SERVER-TEST.jvm'
  environment:
    name: test
    url: https://modesti-test.cern.ch
  only:
  - master
  
quality_preview:
  stage: sonar_preview
  script:
    - ./gradlew sonarqube -Dsonar.host.url=https://en-ice-sonar.cern.ch -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -PartifactoryUser=${ARTIFACTORY_USERNAME} -PartifactoryPassword=${ARTIFACTORY_PASSWORD}
  except:
    - master
  
quality_assurance:
  stage: sonar
  script:
    - ./gradlew dependencyCheckAnalyze sonarqube -Dsonar.host.url=https://en-ice-sonar.cern.ch -PartifactoryUser=${ARTIFACTORY_USERNAME} -PartifactoryPassword=${ARTIFACTORY_PASSWORD}
  only:
    - master