image: java:8

gradle:
  script:
    - ./gradlew clean build publish --debug --stacktrace -PartifactoryUser=${ARTIFACTORY_USERNAME} -PartifactoryPassword=${ARTIFACTORY_PASSWORD} -Djava.security.egd=file:/dev/./urandom
