stages:
- build
- deploy

# Fully build and publish master branch
build_and_publish:
  stage: build
  script:
    - ./gradlew clean publish --refresh-dependencies -PartifactoryUser=${ARTIFACTORY_USERNAME} -PartifactoryPassword=${ARTIFACTORY_PASSWORD}
  only:
    - master

# Just run tests on feature branches
build:
  stage: build
  script:
    - ./gradlew clean test --refresh-dependencies -PartifactoryUser=${ARTIFACTORY_USERNAME} -PartifactoryPassword=${ARTIFACTORY_PASSWORD}
  except:
    - master

deploy_test:
  stage: deploy
  script:
    - source ./gradle.properties; ssh timtest@modesti-test.cern.ch "~/scripts/deploy-modesti-server-test.sh $version"
    - ssh timtest@modesti-test.cern.ch '/usr/opt/bin/wreboot -N MODESTI-SERVER-TEST.jvm'
  environment:
    name: test
    url: https://modesti-test.cern.ch
  only:
  - master
