# Fully build and publish master branch
build_and_publish:
  script:
    - ./gradlew clean publish --refresh-dependencies -PartifactoryUser=${ARTIFACTORY_USERNAME} -PartifactoryPassword=${ARTIFACTORY_PASSWORD}
  only:
    - master

# Just run tests on feature branches
build:
  script:
    - ./gradlew clean test
  except:
    - master

